version: 0.2

env:
  variables:
    FRONTEND_BUCKET: "dropshipping-frontend"
    CLOUDFRONT_DISTRIBUTION: "EU2GD4RRXDM86"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd Frontend
      - npm ci

  build:
    commands:
      - echo "Building frontend..."
      - npm run build

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET --delete

      - echo "Invalidating CloudFront..."
      - aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION \
          --paths "/*"

artifacts:
  files:
    - '**/*'