apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: dropshipping-prod

data:
  PORT: "4000"
  NODE_ENV: "production"
  GOOGLE_REDIRECT_URI: "http://localhost:4000/api/auth/google/callback"
  FRONTEND_URL: "http://16.16.115.136"
  CLIENT_URL: "http://16.16.115.136/admin"
  COOKIE_SECURE: "false"
  SWAGGER_BASE_URL: "http://16.16.115.136"
  EMAIL_USER: "tusharrawat671@gmail.com"
  GOOGLE_CLIENT_ID: ""