
apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: dropshipping-prod

type: Opaque

stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/dropshipping"
  JWT_SECRET: "Tusharsecretkey123"
  EMAIL_PASS: "srrbslnqnpzbxfxz/"
  GOOGLE_CLIENT_SECRET: "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"




  