global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend

    metrics_path: /api/metrics

    static_configs:
      - targets:
          - dropshipping-alb-986894571.eu-north-1.elb.amazonaws.com