name: Trigger AWS CodePipelines

on:
  push:
    branches:
      - codepipeline

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      admin: ${{ steps.filter.outputs.admin }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed folders
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'Frontend/**'
            backend:
              - 'backend/**'
            admin:
              - 'AdminPanel/**'

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Trigger Frontend Pipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name dropshipping-frontend

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Trigger Backend Pipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name dropshipping-pipeline

  admin:
    needs: changes
    if: needs.changes.outputs.admin == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Trigger Admin Pipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name dropshipping-admin